### PR TITLE
Fix typo 'some' -> 'same'

### PR DESCRIPTION
**Pull request by 3onyc**

### CODE REVIEW

**Comment by prashnts** [comment]
I actually _did_ mean to write `some` there. Is that incorrect? Feel free to reopen the PR if you feel so. Thanks!

**Comment by 3onyc** [comment]
If `deserve the some color love` sort of means `deserve some colors to play with` then it's correct, albeit an oddly worded sentence.

**Comment by prashnts** [comment]
Wow, my bad! I actually did _not_ notice the `the` there! Thanks for this, I am merging. Trust me, read this several times, ignoring the existence of `the`! 😩

**Comment by 3onyc** [comment]
Removing the `the` would've been better then, but this works.

**Pull request merged**
